### ISSUE TITLE
General partial wayback machine outage?

### ISSUE THREAD

**Issue by newsjunkie247** [internetarchive/wayback-machine-webextension#999] opened 2023-11-04 16:39 UTC
Since last night there seems to be some sort of general issue with adding new links to the Wayback machine that is also impacting the extension. Extension can't add new links at all and doesn't show page counter, via the website pages can be added, but it says there is a delay in registering them, and testing the API shows a "too man requests" page.

**Comment by fireattack** [comment] 2023-11-05 10:24
Can confirm the issue.

The API call for showing relevant info of each webpage:
```
https://chrome-api.archive.org/__wb/sparkline?collection=web&output=json&url=https%3A%2F%2Fgithub.com%2Finternetarchive%2Fwayback-machine-webextension%2Fissues%2F999
```

never loads.

**Comment by VetaLioSTV** [comment] 2023-11-05 18:21
Several days as extension became broken. Its just shows "wayback machine unavailable" :\

**Comment by exurd** [comment] 2023-11-05 19:19
Seems to be working for me now.

**Comment by VetaLioSTV** [comment] 2023-11-06 21:32
> Seems to be working for me now.

i confirm this, but what excatly happened and why? Lol..

**Comment by exurd** [comment] 2023-12-03 00:02
It's not broken, it's that capturing has been delayed by a few hours; up to 12 hours in some cases.

![chrome_hRptulezyZ_2023-12-03_00-00-46](https://github.com/internetarchive/wayback-machine-webextension/assets/7785022/10e94846-26ab-4a68-b726-b82b98189a1f)

**Comment by ramazansancar** [comment] 2023-12-15 23:16
> It's not broken, it's that capturing has been delayed by a few hours; up to 12 hours in some cases. What is currently happening is different to what happened when the issue was created.
@exurd 
Since this system is designed to work at the lowest cost, it queues up the requests that come in at high density, puts them in the recording list, and gives you an estimated time according to the number in the queue.

I estimate this information by obtaining it from the sources listed below.

- https://en.wikipedia.org/wiki/PetaBox
- https://archive.org/web/petabox.php
- https://blog.archive.org/2010/07/27/the-fourth-generation-petabox/

**Comment by anishsarangi** [comment] 2024-02-07 17:20
Hello Everyone, thank you for reporting this issue. Yes, it was due to the outrage and we were aware of it.
I am closing this as this is resolved.
Thank you.

**Closed as completed by anishsarangi** 2024-02-07 17:20 UTC

**Comment by dserodio** [comment] 2024-02-14 20:23
> Hello Everyone, thank you for reporting this issue. Yes, it was due to the outrage and we were aware of it. I am closing this as this is resolved. Thank you.

@anishsarangi I'm seeing this error right now, it is caused by another outage?
